version: '3.7'

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    cap_add:
      - NET_ADMIN
    networks:
      home_net:
        ipv4_address: 192.168.0.53
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 68/udp
      - 68/tcp
      - 80/tcp
      - 853/tcp
      - 3000/tcp
    restart: unless-stopped
    volumes:
      - $USERDIR/adguard/workdir:/opt/adguardhome/work
      - $USERDIR/adguard/config:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.adguard-rtr.entrypoints=https"
      - "traefik.http.routers.adguard-rtr.rule=HostHeader(`adguard.$DOMAINNAME`)"
      - "traefik.http.routers.adguard-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.adguard-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.adguard-rtr.service=adguard-svc"
      - "traefik.http.services.adguard-svc.loadbalancer.server.port=3000"
networks:
  home_net:
    external: true
