version: "3.7"

# Dronce-ci server
services: 
  drone-server:
    container_name: drone-server
    image: drone/drone:latest
    restart: unless-stopped
    networks:
      home_net:
        ipv4_address: 192.168.0.98
    environment:
      - DRONE_SERVER_HOST=ci.$DOMAINNAME
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=false
      - DRONE_RPC_SECRET=c91aa70bc9421b639a6125f92c6d2e8e
      - DRONE_COOKIE_SECRET=1c6822003b53f12f6b8b1ecc72c71d05
      - DRONE_COOKIE_TIMEOUT=720h
      - DRONE_GITEA_CLIENT_ID=$GITEA_CLIENT_ID
      - DRONE_GITEA_CLIENT_SECRET=$GITEA_CLIENT_SECRET
      - DRONE_GITEA_SERVER=https://git.$DOMAINNAME
      - DRONE_LOGS_DEBUG=false
      - DRONE_CRON_DISABLED=true
    volumes:
      - $VOLUME/drone:/data
    ports:
      - "9000:80"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.drone-rtr.entrypoints=https"
      - "traefik.http.routers.drone-rtr.rule=HostHeader(`ci.$DOMAINNAME`)"
      - "traefik.http.routers.drone-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.drone-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.drone-rtr.service=drone-svc"
      - "traefik.http.services.drone-svc.loadbalancer.server.port=80"
  runner:
    image: drone/drone-runner-docker:latest
    networks:
      home_net:
        ipv4_address: 192.168.0.99
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=c91aa70bc9421b639a6125f92c6d2e8e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  home_net:
    external: true