version: "3.7"

services:  
    heimdall:
      container_name: heimdall
      image: linuxserver/heimdall:latest
      restart: unless-stopped
      networks:
        home_net:
          ipv4_address: 192.168.0.72
      security_opt:
        - no-new-privileges:true
      ports:
        - "80:80"
      volumes:
        - $USERDIR/heimdall:/config
      environment:
        - PUID=$PUID
        - PGID=$PGID
        - TZ=$TZ
      labels:
        - "traefik.enable=true"
        ## HTTP Routers
        - "traefik.http.routers.heimdall-rtr.entrypoints=https"
        - "traefik.http.routers.heimdall-rtr.rule=HostHeader(`hub.$DOMAINNAME`)"
        - "traefik.http.routers.heimdall-rtr.tls=true"
        ## Middlewares
        - "traefik.http.routers.heimdall-rtr.middlewares=chain-authelia@file"
        ## HTTP Services
        - "traefik.http.routers.heimdall-rtr.service=heimdall-svc"
        - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"

networks:
  home_net:
    external: true
