version: "3.7"

services:  
  # MinIO Object storage
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-10-16T04-13-43Z
    restart: always
    networks:
      home_net:
        ipv4_address: 192.168.0.81
    ports:
      - "9000:9000"
    volumes:
      - $VOLUME/minio/:/mnt/data
    environment:
      MINIO_ROOT_USER: "$MY_USERNAME"
      MINIO_ROOT_PASSWORD: "$MY_PASSWORD"
      MINIO_VOLUMES: "/mnt/data"
      MINIO_BROWSER_REDIRECT_URL: "https://minio-web.$DOMAINNAME"
      MINIO_SERVER_URL: "https://minio.$DOMAINNAME"
    command: minio server --console-address ":9090"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.minio-rtr.entrypoints=https"
      - "traefik.http.routers.minio-rtr.rule=HostHeader(`minio.$DOMAINNAME`)"
      - "traefik.http.routers.minio-rtr.tls=true"
      ## Web Console Router
      - "traefik.http.routers.minio-rtr-admin.entrypoints=https"
      - "traefik.http.routers.minio-rtr-admin.rule=HostHeader(`minio-web.$DOMAINNAME`)"
      - "traefik.http.routers.minio-rtr-admin.tls=true"
      ## Middlewares
      - "traefik.http.routers.minio-rtr.middlewares=chain-no-auth@file"

      - "traefik.http.routers.minio-rtr-admin.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.minio-rtr.service=minio-svc"
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9000"
      
      - "traefik.http.routers.minio-rtr-admin.service=minio-svc-admin"
      - "traefik.http.services.minio-svc-admin.loadbalancer.server.port=9090"

networks:
  home_net:
    external: true
