version: "3.7"

services:  
  # Music Server
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: always
    networks:
      home_net:
        ipv4_address: 192.168.0.79
    ports:
      - "4533:4533"
    volumes:
      - $VOLUME/navidrome/data:/data
      - $VOLUME/navidrome/music:/music:ro
    environment:
      TZ: $TZ
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.navidrome-rtr.entrypoints=https"
      - "traefik.http.routers.navidrome-rtr.rule=HostHeader(`music.$DOMAINNAME`)"
      - "traefik.http.routers.navidrome-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.navidrome-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.navidrome-rtr.service=navidrome-svc"
      - "traefik.http.services.navidrome-svc.loadbalancer.server.port=4533"

networks:
  home_net:
    external: true
