version: "3.7"
services:  
    # paste bin with syntax highlighting 
  pastefy:
    container_name: pastefy
    hostname: pastefy
    image: interaapps/pastefy:latest
    networks:
      home_net:
        ipv4_address: 192.168.0.77
    ports:
      - "9999:80"
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: pastefy
      DATABASE_USER: pastefy
      DATABASE_PASSWORD: $PASTIFY_DB_PASS
      DATABASE_HOST: 192.168.0.64 
      DATABASE_PORT: 3306
      OAUTH2_INTERAAPPS_CLIENT_ID: $PASTIFY_OAUTH_ID
      OAUTH2_INTERAAPPS_CLIENT_SECRET: $PASTIFY_OAUTH_SECRET
      PASTEFY_LOGIN_REQUIRED_CREATE: "true"
      PASTEFY_GRANT_ACCESS_REQUIRED: "true"
      SERVER_NAME: http://paste.$DOMAINNAME
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pastefy-rtr.entrypoints=https"
      - "traefik.http.routers.pastefy-rtr.rule=HostHeader(`paste.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.pastefy-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.pastefy-rtr.service=pastefy-svc"
      - "traefik.http.services.pastefy-svc.loadbalancer.server.port=80"

networks:
  home_net:
    external: true
