version: "3.7"

# Redis - Key-value Store
services: 
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes
    networks:
      home_net:
        ipv4_address: 192.168.0.70
    ports:
      - "6379:6379"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  home_net:
    external: true
